name: CI/CD Pipeline for Multiple Disease Prediction

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t saihemanthvarma/multiple-disease-prediction .
          docker tag saihemanthvarma/multiple-disease-prediction saihemanthvarma/multiple-disease-prediction:${{ github.sha }}
          docker push saihemanthvarma/multiple-disease-prediction:${{ github.sha }}
          docker push saihemanthvarma/multiple-disease-prediction:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add Server to Known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            docker pull saihemanthvarma/multiple-disease-prediction:${{ github.sha }}
            docker stop multiple-disease-prediction || true
            docker rm multiple-disease-prediction || true
            docker run -d \
              -p 8501:8501 \
              --name multiple-disease-prediction \
              --restart unless-stopped \
              saihemanthvarma/multiple-disease-prediction:${{ github.sha }}
            docker system prune -af || true
