name: CI/CD Pipeline for Multiple Disease Prediction

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t saihemanthvarma/multiple-disease-prediction .
          docker tag saihemanthvarma/multiple-disease-prediction saihemanthvarma/multiple-disease-prediction:${{ github.sha }}
          docker push saihemanthvarma/multiple-disease-prediction:${{ github.sha }}
          docker push saihemanthvarma/multiple-disease-prediction:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts || true

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT || 22 }}
          script: |
            # Pull the new image
            docker pull saihemanthvarma/multiple-disease-prediction:${{ github.sha }}
            
            # Stop and remove old container
            docker stop multiple-disease-prediction || true
            docker rm multiple-disease-prediction || true
            
            # Run new container
            docker run -d \
              -p 8501:8501 \
              --name multiple-disease-prediction \
              --restart unless-stopped \
              -e NODE_ENV=production \
              saihemanthvarma/multiple-disease-prediction:${{ github.sha }}
            
            # Cleanup
            docker image prune -af
