name: CI/CD Pipeline for Multiple Disease Prediction

on:
  push:
    branches:
      - main  # Runs workflow on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t saihemanthvarma/multiple-disease-prediction .
          docker tag saihemanthvarma/multiple-disease-prediction saihemanthvarma/multiple-disease-prediction:latest
          docker push saihemanthvarma/multiple-disease-prediction:latest

  deploy:
    needs: build  # Runs only if the build job is successful
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH Key for Deployment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Use ssh-keyscan to fetch the server's public key and add it to known_hosts
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22  # You can change this if your server uses a custom port
          script: |
            docker pull saihemanthvarma/multiple-disease-prediction:latest
            docker stop multiple-disease-prediction || true
            docker rm multiple-disease-prediction || true
            docker run -d -p 8501:8501 --name multiple-disease-prediction saihemanthvarma/multiple-disease-prediction:latest
