name: CI/CD Pipeline for Multiple Disease Prediction

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Docker Buildx for building multi-platform Docker images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build the Docker image and push to Docker Hub with both commit SHA and latest tag
      - name: Build and Push Docker Image
        run: |
          docker build -t saihemanthvarma/multiple-disease-prediction .  # Build the Docker image
          docker tag saihemanthvarma/multiple-disease-prediction saihemanthvarma/multiple-disease-prediction:${{ github.sha }}  # Tag image with SHA
          docker push saihemanthvarma/multiple-disease-prediction:${{ github.sha }}  # Push with commit SHA tag
          docker push saihemanthvarma/multiple-disease-prediction:latest  # Push with latest tag

  deploy:
    needs: build  # Ensure build job is completed before deploying
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up SSH key for deployment to the server
      - name: Set up SSH Key for Deployment
        run: |
          mkdir -p ~/.ssh  # Create the .ssh directory
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa  # Write SSH key to id_rsa file
          chmod 700 ~/.ssh  # Secure the .ssh directory
          chmod 600 ~/.ssh/id_rsa  # Ensure private key is secure
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts  # Add the server's host key to known_hosts

      # SSH into the server and deploy the Docker image
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}  # Server IP or Hostname
          username: ${{ secrets.SERVER_USER }}  # SSH username on the server
          key: ${{ secrets.SERVER_SSH_KEY }}  # SSH private key for authentication
          port: 22  # Ensure the SSH port is correct (default is 22)
          script: |
            docker pull saihemanthvarma/multiple-disease-prediction:${{ github.sha }}  # Pull the new Docker image
            docker stop multiple-disease-prediction || true  # Stop any running container (if exists)
            docker rm multiple-disease-prediction || true  # Remove the old container
            docker run -d -p 8501:8501 --name multiple-disease-prediction saihemanthvarma/multiple-disease-prediction:${{ github.sha }}  # Run the new container

